site_name: Causemos Help
site_author: Uncharted Software Inc.

copyright: Copyright &copy; 2023 Uncharted Software Inc.

theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: causemos
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/causemos-icon-white.svg
  favicon: img/favicon.ico
  font: false
  language: custom

plugins:
    search: {}
    glightbox: {}
    macros: {}

extra:
  social:
    - icon: fontawesome/brands/uncharted
      link: https://uncharted.software
      name: Uncharted Software
  product_name: Causemos
  build: core

markdown_extensions:
    admonition: {}
    attr_list: {}
    def_list: {}
    md_in_html: {}
    pymdownx.details: {}
    pymdownx.superfences: {}
    pymdownx.tabbed:
      alternate_style: true 
    pymdownx.keys: {}
    pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css

nav:
  - About:
    - index.md
  - Get started: get-started.md
  - Create an analysis project: analysis-projects.md
  - Build an index graph: index-graph.md
  - Search datacubes: search-datacubes.md
  - Rank regions: rank-regions.md
  - View projections: projections.md
  - Save and share insights: insights.md